apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-username: <base64-username>
  mongodb-password: <base64-password>

---
apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
type: Opaque
data:
  app-secret-key: <base64-secret-key>
